import { ethers } from "hardhat";
import fs from "node:fs";
import path from "node:path";

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("Deploying contracts with the account:", deployer.address);

  const OutguessDuel = await ethers.getContractFactory("OutguessDuel");

  // Note: This deploys with NO constructor arguments.
  // This ONLY works if you replaced your contract with the Native ETH version.
  const duel = await OutguessDuel.deploy();
  await duel.waitForDeployment();

  const contractAddress = await duel.getAddress();

  console.log("OutguessDuel deployed to:", contractAddress);

  const root = process.cwd();

  // Backend reads this file.
  fs.writeFileSync(
    path.join(root, ".deploy-address"),
    contractAddress
  );

  // Frontend imports this generated file.
  const generatedDir = path.join(root, "frontend", "src", "generated");
  const generatedFile = path.join(generatedDir, "contract.ts");

  fs.mkdirSync(generatedDir, { recursive: true });

  fs.writeFileSync(
    generatedFile,
    `// This file is generated by scripts/deploy-local.ts
// Do not edit manually.
export const DEPLOYED_CONTRACT_ADDRESS = '${contractAddress}'
`
  );

  console.log("Wrote contract address to .deploy-address");
  console.log("Wrote frontend generated contract address to:", generatedFile);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});